name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi



    - name: Build custom http error
      run: cd custom_http_error && go build -v -o custom_http_error
    
    - name: Upload custom_http_error
      uses: actions/upload-artifact@v1
      with:
        name: custom_http_error
        path: ./custom_http_error/custom_http_error



    - name: Build custom struct error
      run: cd custom_struct_error && go build -v -o custom_struct_error

    - name: Upload custom_struct_error
      uses: actions/upload-artifact@v1
      with:
        name: custom_struct_error
        path: ./custom_struct_error/custom_struct_error



    - name: Build errors package
      run: cd errors_package && go build -v -o errors_package
      
    - name: Upload errors_package
      uses: actions/upload-artifact@v1
      with:
        name: errors_package
        path: ./errors_package/errors_package



    - name: Build type assertion
      run: cd type_assertion && go build -v -o type_assertion

    - name: Upload type assertion
      uses: actions/upload-artifact@v1
      with:
        name: type_assertion
        path: ./type_assertion/type_assertion
